# This is a basic workflow to help you get started with Actions

name: Auto Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Changelog:

    runs-on: ubuntu-latest

    outputs:
      shouldCreateRelease: ${{ steps.changelog.outputs.shouldCreateRelease }}
      shouldCreatePDF: ${{ steps.changelog.outputs.shouldCreatePDF }}
      version: ${{ steps.changelog.outputs.version }}
      release: ${{ steps.changelog.outputs.release }}
      changelog: ${{ steps.changelog.outputs.changelog }}

    steps:
      - uses: actions/checkout@v2
      - name: Read the Releases File
        id: changelog
        uses: Jeconias/changelog@v1.3
        with:
          path: "./RELEASES.md"
      - run: echo "${{steps.changelog.outputs.changelog}}"

  html_to_pdf:

    needs: Changelog
    if: needs.Changelog.outputs.shouldCreateRelease == 'true' && needs.Changelog.outputs.shouldCreatePDF == 'true'

    runs-on: ubuntu-latest
    name: Generate CV
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Jekyll CV
        uses: mbursi/jekyll-build-only-action@v1.0.0
      - name: Build PDF CV
        # You may pin to the exact commit or the version.
        # uses: fifsky/html-to-pdf-action@44d977811fe614e8eba4471a108f6bd355709ddd
        uses: fifsky/html-to-pdf-action@v0.0.2
        with:
          # html file path
          htmlFile: ./_site/index.html
          # output file path
          outputFile: ./Ezequiel_Veliz_CV.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - name: Upload PDF CV
        uses: actions/upload-artifact@v2
        with:
          name: CV_PDF
          path: ./Ezequiel_Veliz_CV.pdf

  Full_Release:
  
    needs: [Changelog, html_to_pdf]
    if: needs.Changelog.outputs.shouldCreateRelease == 'true' && needs.Changelog.outputs.shouldCreatePDF == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: CV_PDF

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        uses: Hs1r1us/Release-AIO@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.Changelog.outputs.version }}
          release_name: ${{ needs.Changelog.outputs.release }}
          body: ${{needs.Changelog.outputs.changelog}}
          asset_files: './Ezequiel_Veliz_CV.pdf'

  Simple_Release:

    needs: [Changelog]
    if: needs.Changelog.outputs.shouldCreateRelease == 'true' && needs.Changelog.outputs.shouldCreatePDF == 'false'

    runs-on: ubuntu-latest

    steps:

      - name: Create Release
        uses: Hs1r1us/Release-AIO@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.Changelog.outputs.version }}
          release_name: ${{ needs.Changelog.outputs.release }}
          body: ${{needs.Changelog.outputs.changelog}}