name: Build Pdf

on:
  create:
    tags:
      - v*

jobs:
  html_to_pdf:
    runs-on: ubuntu-latest
    name: Generate CV
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Jekyll CV
        uses: mbursi/jekyll-build-only-action@v1.0.0
      - name: Build PDF CV
        # You may pin to the exact commit or the version.
        # uses: fifsky/html-to-pdf-action@44d977811fe614e8eba4471a108f6bd355709ddd
        uses: fifsky/html-to-pdf-action@v0.0.2
        with:
          # html file path
          htmlFile: ./_site/index.html
          # output file path
          outputFile: ./Ezequiel_Veliz_CV.pdf
      - name: Upload PDF CV
        uses: actions/upload-artifact@v2
        with:
          name: CV PDF
          path: ./Ezequiel_Veliz_CV.pdf
      - name: Release CV
        uses: SierraSoftworks/gh-releases@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: 'true'
          files: Ezequiel_Veliz_CV.pdf
    
