name: Build Pdf

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  html_to_pdf:
    runs-on: ubuntu-latest
    name: get_artifact
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
        name: my-artifact

    - name: Display structure of downloaded files
      run: ls -R
    
