name: Build Pdf

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  html_to_pdf:
    runs-on: ubuntu-latest
    name: get_artifact
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: jekyll build
        uses: mbursi/jekyll-build-only-action@v1.0.0
      - name: Display structure of downloaded files
        run: ls -R
    
